# Ultralytics YOLO 🚀, AGPL-3.0 license

name: CLA Assistant
on:
  issue_comment:
    types:
      - created
  pull_request_target:
    types:
      - reopened
      - opened
      - synchronize

jobs:
  CLA:
    if: github.repository == 'ultralytics/ultralytics'
    runs-on: ubuntu-latest
    steps:
      - name: CLA Assistant
        if: (github.event.comment.body == 'recheck' || github.event.comment.body == 'I have read the CLA Document and I sign the CLA') || github.event_name == 'pull_request_target'
        uses: contributor-assistant/github-action@v2.3.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          # must be repository secret token
          PERSONAL_ACCESS_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
        with:
          path-to-signatures: 'signatures/version1/cla.json'
          path-to-document: 'https://docs.ultralytics.com/help/CLA' # CLA document
          # branch should not be protected
          branch: 'main'
          allowlist: dependabot[bot],github-actions,[pre-commit*,pre-commit*,bot*

          remote-organization-name: ultralytics
          remote-repository-name: cla
          custom-pr-sign-comment: 'I have read the CLA Document and I sign the CLA'
          custom-allsigned-prcomment: All Contributors have signed the CLA. ✅
          #custom-notsigned-prcomment: 'pull request comment with Introductory message to ask new contributors to sign'
